### PR TITLE
Proof Read Grammar Edits

### PR DESCRIPTION
**Pull request by WorthersLegion**
Edited line 13,17, 35, 43, 45, 56, 58, 79, 81, 93, 95, 99, 102, 103, 111, 112, 114, 117, 118, 
Line 124... I am not sure if you mean happens or happened... Both work but you are using 2 in one and they mean different things. So far I have just made edits to small Grammatical errors like punctuation and "sended". I noticed you used that quite a bit. The proper way is "sent" Also I want to point out, I am not... I feel like I am being a grammar nazi over here. xD 
132, 147, 151, 
Also on lines, 158, 162, 166, and 174, "Some thing" works but "something" would be proper. I have not changed this as I wanted to run it by you first. Same with line 124 that I talked about above. I need to know what you meant on that one before I can move forward
184, 217, and lastly 269. 

Most errors I found were fairly small. Things being plural when they shouldn't be or vice versa, extra characters on words, sended instead of sent, etc. I hope this is sorta (at least) what you meant by giving info on what I changed... I'll try to be more in depth about what I change next time but with a thing this big, it is quite time-consuming to do that and I wouldn't have been able to edit this in 20 minutes like I did, doing that.

### CODE REVIEW

**Comment by android4682** [comment]
Thanks will review this soon.

**Comment by WorthersLegion** [comment]
No problem :D I will wait for the go-ahead to move forward with another task. I don't want to do something you don't like and then I wind up doing the same thing in future tasks. :D

**Comment by Axiatinc** [comment]
Approved :)

**Comment by WorthersLegion** [comment]
Of course guys! Happy to help! :D I will work on the next now :D

**Comment by android4682** [comment]
This was in depth enough XD
No need to make it more in depth (unless you think it's necessary).
Most of those mistaks are because my brain tries to do 3 things at once but thanks for the changes.

**Pull request merged**
